version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: kptdb

  kptbackend-docker:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GOOGLE_ID=${GOOGLE_ID}
      - GOOGLE_SECRET=${GOOGLE_SECRET}
      - OPENAI_KEY=${OPENAI_KEY}
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/kptdb
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "8081:8081"
    depends_on:
      - mysql


  kptnext-docker:
    args:
      NEXT_PUBLIC_BACKEND_URL: http://localhost:8081
    environment:
      - GOOGLE_ID=${GOOGLE_ID}
      - GOOGLE_SECRET=${GOOGLE_SECRET}
      - NODE_ENV=DEBUG
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8081
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    build:
      context: ../kptnext
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - spring-boot-app