server:
  port: 8081

logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG


spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: {clientid}
            client-secret: {clientsecret}