server:
  port: 8081

logging:
  level:
    root: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.apache.http: DEBUG
    httpclient.wire: DEBUG
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE-CLIENTID}
            client-secret: ${GOOGLE-SECRET}

openai:
  model: gpt-3.5-turbo
  http-client:
    read-timeout: 60000
    connect-timeout: 60000
  api:
    url: /chat/completions
    key: ${OPENAI-KEY}
    base-url: https://api.openai.com/v1
